# Import `torch` library

In [1]:
import torch
print(torch.__version__)

2.1.2


---

## Create a tensor

- `torch.tensor()`

In [2]:
scalar = torch.tensor(7)
print(f"tensor : {scalar}")
print(f"dtype  : {scalar.dtype}")
print(f"item() : {scalar.item()}")
print(f"ndim   : {scalar.ndim}")
print(f"shape  : {scalar.shape}")

tensor : 7
dtype  : torch.int64
item() : 7
ndim   : 0
shape  : torch.Size([])


In [3]:
vector = torch.tensor([5, 9])

print(f"tensor : {vector}")
print(f"dtype  : {vector.dtype}")
print(f"item() : {vector[0].item(), vector[1].item()}")
print(f"ndim   : {vector.ndim}")
print(f"shape  : {vector.shape}")

tensor : tensor([5, 9])
dtype  : torch.int64
item() : (5, 9)
ndim   : 1
shape  : torch.Size([2])


In [4]:
MATRIX = torch.tensor([
    [2, 3, 4, 5],
    [6, 8, 7, 9],
])

print(MATRIX)
print(f"dtype  : {MATRIX.dtype}")
print(f"ndim   : {MATRIX.ndim}")
print(f"shape  : {MATRIX.shape}")
print("-" * 50)

print(MATRIX[:, 0])
print(MATRIX[:, 1])
print(MATRIX[:, 2])
print(MATRIX[:, 3])
print("-" * 50)

print(MATRIX[0, :])
print(MATRIX[1, :])


tensor([[2, 3, 4, 5],
        [6, 8, 7, 9]])
dtype  : torch.int64
ndim   : 2
shape  : torch.Size([2, 4])
--------------------------------------------------
tensor([2, 6])
tensor([3, 8])
tensor([4, 7])
tensor([5, 9])
--------------------------------------------------
tensor([2, 3, 4, 5])
tensor([6, 8, 7, 9])


In [5]:
a = MATRIX[1]
b = MATRIX[1, :]

print(a.shape)
print(b.shape)
print(torch.equal(a, b))

torch.Size([4])
torch.Size([4])
True


In [6]:
TENSOR = torch.tensor([
    [
        [2, 3, 6],
        [6, 8, 7],
        [3, 5, 1],
    ],
    [
        [-2, -3, -6],
        [-6, -8, -7],
        [-3, -5, -1],
    ],
])

print(f"tensor:\n{TENSOR}")
print(f"dtype  : {TENSOR.dtype}")
print(f"ndim   : {TENSOR.ndim}")
print(f"shape  : {TENSOR.shape}")
print("-" * 50)

print(TENSOR[0])
print(TENSOR[0, 1])
print(TENSOR[0, 1, 2])
print("-" * 50)

print(TENSOR[1])
print(TENSOR[1, 1])
print(TENSOR[1, 1, 2])


tensor:
tensor([[[ 2,  3,  6],
         [ 6,  8,  7],
         [ 3,  5,  1]],

        [[-2, -3, -6],
         [-6, -8, -7],
         [-3, -5, -1]]])
dtype  : torch.int64
ndim   : 3
shape  : torch.Size([2, 3, 3])
--------------------------------------------------
tensor([[2, 3, 6],
        [6, 8, 7],
        [3, 5, 1]])
tensor([6, 8, 7])
tensor(7)
--------------------------------------------------
tensor([[-2, -3, -6],
        [-6, -8, -7],
        [-3, -5, -1]])
tensor([-6, -8, -7])
tensor(-7)


---

## Tensor with random values

- `torch.rand()`

- `torch.randn()`

- `torch.randint()`


In [7]:
torch.manual_seed(42)
random_tensor = torch.rand(1, 3, 4)

print(f"tensor:\n{random_tensor}")
print(f"dtype  : {random_tensor.dtype}")
print(f"ndim   : {random_tensor.ndim}")
print(f"shape  : {random_tensor.shape}")

tensor:
tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]])
dtype  : torch.float32
ndim   : 3
shape  : torch.Size([1, 3, 4])


In [8]:
torch.manual_seed(42)
random_tensor = torch.randn(1, 3, 4)

print(f"tensor:\n{random_tensor}")
print(f"dtype  : {random_tensor.dtype}")
print(f"ndim   : {random_tensor.ndim}")
print(f"shape  : {random_tensor.shape}")

tensor:
tensor([[[ 0.3367,  0.1288,  0.2345,  0.2303],
         [-1.1229, -0.1863,  2.2082, -0.6380],
         [ 0.4617,  0.2674,  0.5349,  0.8094]]])
dtype  : torch.float32
ndim   : 3
shape  : torch.Size([1, 3, 4])


In [9]:
torch.manual_seed(42)
random_tensor = torch.randint(low=1, high=30, size=(1, 3, 4))

print(f"tensor\n:{random_tensor}")
print(f"dtype  : {random_tensor.dtype}")
print(f"ndim   : {random_tensor.ndim}")
print(f"shape  : {random_tensor.shape}")

tensor
:tensor([[[ 3, 12, 22, 22],
         [27,  2,  2, 28],
         [13, 29, 29, 22]]])
dtype  : torch.int64
ndim   : 3
shape  : torch.Size([1, 3, 4])


In [10]:
# Create a random tensor of size (224, 224, 3)
torch.manual_seed(42)
random_image_size_tensor = torch.rand(size=(224, 224, 3))

print(f"dtype  : {random_image_size_tensor.dtype}")
print(f"ndim   : {random_image_size_tensor.ndim}")
print(f"shape  : {random_image_size_tensor.shape}")

dtype  : torch.float32
ndim   : 3
shape  : torch.Size([224, 224, 3])


---

## zeros, ones, arange, zeros_like, ones_like

- `torch.zeros()`

- `torch.ones()`

- `torch.arange()`

- `torch.zeros_like()`

- `torch.ones_like()`


In [11]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))

print(f"tensor:\n{zeros}")
print(f"dtype  : {zeros.dtype}")
print(f"ndim   : {zeros.ndim}")
print(f"shape  : {zeros.shape}")

tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
dtype  : torch.float32
ndim   : 2
shape  : torch.Size([3, 4])


In [12]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))

print(f"tensor:\n{ones}")
print(f"dtype  : {ones.dtype}")
print(f"ndim   : {ones.ndim}")
print(f"shape  : {ones.shape}")

tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
dtype  : torch.float32
ndim   : 2
shape  : torch.Size([3, 4])


In [13]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)

print(f"tensor:\n{zero_to_ten}")
print(f"dtype  : {zero_to_ten.dtype}")
print(f"ndim   : {zero_to_ten.ndim}")
print(f"shape  : {zero_to_ten.shape}")

tensor:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
dtype  : torch.int64
ndim   : 1
shape  : torch.Size([10])


In [14]:
# Create a range of values 0 to 10
zero_to_ten_float = torch.arange(start=0, end=10, step=1, dtype=torch.float)

print(f"tensor:\n{zero_to_ten_float}")
print(f"dtype  : {zero_to_ten_float.dtype}")
print(f"ndim   : {zero_to_ten_float.ndim}")
print(f"shape  : {zero_to_ten_float.shape}")

tensor:
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
dtype  : torch.float32
ndim   : 1
shape  : torch.Size([10])


In [15]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape

print(f"tensor:\n{ten_zeros}")
print(f"dtype  : {ten_zeros.dtype}")
print(f"ndim   : {ten_zeros.ndim}")
print(f"shape  : {ten_zeros.shape}")

tensor:
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
dtype  : torch.int64
ndim   : 1
shape  : torch.Size([10])


In [16]:
# Can also create a tensor of zeros similar to another tensor
ten_ones = torch.ones_like(input=zero_to_ten) # will have same shape

print(f"tensor:\n{ten_ones}")
print(f"dtype  : {ten_ones.dtype}")
print(f"ndim   : {ten_ones.ndim}")
print(f"shape  : {ten_ones.shape}")

tensor:
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
dtype  : torch.int64
ndim   : 1
shape  : torch.Size([10])


---

## Tensor attributes

- `data`: Any,

- `dtype`: _dtype | None = None,

- `device`: Device = None

- `requires_grad`: _bool = False


In [17]:
float_32_tensor = torch.tensor(
    data=[3.0, 6.0, 9.0],
    dtype=None,          # defaults to None, which is torch.float32 or whatever datatype is passed
    device=None,         # defaults to None, which uses the default tensor type
    requires_grad=False, # if True, operations performed on the tensor are recorded
)

print(f"tensor  : {float_32_tensor}")
print(f"dtype   : {float_32_tensor.dtype}")
print(f"ndim    : {float_32_tensor.ndim}")
print(f"shape   : {float_32_tensor.shape}")
print(f"device  : {float_32_tensor.device}")

tensor  : tensor([3., 6., 9.])
dtype   : torch.float32
ndim    : 1
shape   : torch.Size([3])
device  : cpu


In [18]:
float_16_tensor = torch.tensor(
    [3.0, 6.0, 9.0], dtype=torch.float16
)  # torch.half would also work

print(f"tensor  : {float_16_tensor}")
print(f"dtype   : {float_16_tensor.dtype}")
print(f"ndim    : {float_16_tensor.ndim}")
print(f"shape   : {float_16_tensor.shape}")
print(f"device  : {float_16_tensor.device}")

tensor  : tensor([3., 6., 9.], dtype=torch.float16)
dtype   : torch.float16
ndim    : 1
shape   : torch.Size([3])
device  : cpu


In [19]:
x = float_16_tensor * float_32_tensor

print(f"tensor  : {x}")
print(f"dtype   : {x.dtype}")
print(f"ndim    : {x.ndim}")
print(f"shape   : {x.shape}")
print(f"device  : {x.device}")

tensor  : tensor([ 9., 36., 81.])
dtype   : torch.float32
ndim    : 1
shape   : torch.Size([3])
device  : cpu


---

## Operations:

- `torch.add()` or `tensor.add()` or `+`

- `torch.sub()` or `tensor.sub()` or `-`

- `torch.mul()` or `tensor.mul()` or `*`

- `torch.div()` or `tensor.div()` or `/`

- `torch.matmul()` or `tensor.matmul()` or `@`

In [20]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor.add(10))
print(torch.add(tensor, 10))

tensor([11, 12, 13])
tensor([11, 12, 13])
tensor([11, 12, 13])


In [21]:
tensor = torch.tensor([1, 2, 3])
print(tensor - 10)
print(tensor.sub(10))
print(torch.sub(tensor, 10))

tensor([-9, -8, -7])
tensor([-9, -8, -7])
tensor([-9, -8, -7])


In [22]:
tensor = torch.tensor([1, 2, 3])
print(tensor * 10)
print(tensor.mul(10))
print(torch.mul(tensor, 10))

tensor([10, 20, 30])
tensor([10, 20, 30])
tensor([10, 20, 30])


In [23]:
tensor = torch.tensor([1, 2, 3])
print(tensor / 10)
print(tensor.div(10))
print(torch.div(tensor, 10))

tensor([0.1000, 0.2000, 0.3000])
tensor([0.1000, 0.2000, 0.3000])
tensor([0.1000, 0.2000, 0.3000])


In [24]:
x = torch.tensor([[10, 20], [30, 40]])
y = torch.tensor([[-10, -20], [-30, -40]])
print(x @ y)
print(x.matmul(y))
print(torch.matmul(x, y))

tensor([[ -700, -1000],
        [-1500, -2200]])
tensor([[ -700, -1000],
        [-1500, -2200]])
tensor([[ -700, -1000],
        [-1500, -2200]])


---

## type, reshape

- `tensor.type(torch.float)`

- `torch.reshape()` or `tensor.reshape()`

In [25]:
tensor = torch.tensor([1, 2, 3])
print(tensor)
print(tensor.dtype)

float_tensor = tensor.type(torch.float)
print(float_tensor)
print(float_tensor.dtype)

tensor([1, 2, 3])
torch.int64
tensor([1., 2., 3.])
torch.float32


In [26]:
tensor = torch.tensor([[20, 30, 50], [100, 10, 60]])
print(f"tensor:\n{tensor}")
print(f"shape: {tensor.shape}")
print("-" * 50)

reshaped_tensor = torch.reshape(tensor, shape=(6,))
print(f"\nreshaped tensor:\n{reshaped_tensor}")
print(f"dtype: {reshaped_tensor.shape}")
print("-" * 50)

reshaped_tensor = tensor.reshape(shape=(6,))
print(f"\nreshaped tensor:\n{reshaped_tensor}")
print(f"dtype: {reshaped_tensor.shape}")
print("-" * 50)

tensor:
tensor([[ 20,  30,  50],
        [100,  10,  60]])
shape: torch.Size([2, 3])
--------------------------------------------------

reshaped tensor:
tensor([ 20,  30,  50, 100,  10,  60])
dtype: torch.Size([6])
--------------------------------------------------

reshaped tensor:
tensor([ 20,  30,  50, 100,  10,  60])
dtype: torch.Size([6])
--------------------------------------------------


---

## min, max, sum

- `torch.min()` or `tensor.min()`

- `torch.max()` or `tensor.max()`

- `torch.sum()` or `tensor.sum()`


In [27]:
tensor = torch.tensor([[20, 30, 50], [100, 10, 60]])
print(f"tensor:\n{tensor}")

print(f"\n{'-' * 50}")
print("min of entire tensor:")
print(torch.min(tensor))

print(f"\n{'-' * 50}")
print("min of (dim=0):")
result = torch.min(tensor, dim=0)
print(result.values)
print(result.indices)

print(f"\n{'-' * 50}")
print("min of (dim=1):")
result = torch.min(tensor, dim=1)
print(result.values)
print(result.indices)

# print(tensor.min())

# print("\nmin of (dim=0)")
# result = tensor.min(dim=0)
# print(result.values)
# print(result.indices)

# print("\nmin of (dim=1)")
# result = tensor.min(dim=1)
# print(result.values)
# print(result.indices)

tensor:
tensor([[ 20,  30,  50],
        [100,  10,  60]])

--------------------------------------------------
min of entire tensor:
tensor(10)

--------------------------------------------------
min of (dim=0):
tensor([20, 10, 50])
tensor([0, 1, 0])

--------------------------------------------------
min of (dim=1):
tensor([20, 10])
tensor([0, 1])


In [28]:
tensor = torch.tensor([[20, 30, 50], [100, 10, 60]])
print(f"tensor:\n{tensor}")

print(f"\n{'-' * 50}")
print("max of entire tensor:")
print(torch.max(tensor))

print(f"\n{'-' * 50}")
print("max of (dim=0):")
result = torch.max(tensor, dim=0)
print(result.values)
print(result.indices)

print(f"\n{'-' * 50}")
print("max of (dim=1):")
result = torch.max(tensor, dim=1)
print(result.values)
print(result.indices)

# print(tensor.max())

# print("\nmax of dim=0")
# result = tensor.max(dim=0)
# print(result.values)
# print(result.indices)

# print("\nmax of dim=1")
# result = tensor.max(dim=1)
# print(result.values)
# print(result.indices)

tensor:
tensor([[ 20,  30,  50],
        [100,  10,  60]])

--------------------------------------------------
max of entire tensor:
tensor(100)

--------------------------------------------------
max of (dim=0):
tensor([100,  30,  60])
tensor([1, 0, 1])

--------------------------------------------------
max of (dim=1):
tensor([ 50, 100])
tensor([2, 0])


In [29]:
tensor = torch.tensor([[20, 30, 50], [100, 10, 60]])
print(f"tensor:\n{tensor}")

print(f"\n{'-' * 50}")
print("sum of entire tensor:")
print(torch.sum(tensor))


print(f"\n{'-' * 50}")
print("sum of (dim=0):")
result = torch.sum(tensor, dim=0)
print(result)

print(f"\n{'-' * 50}")
print("sum of (dim=1):")
result = torch.sum(tensor, dim=1)
print(result)

# print(tensor.sum())

# print("\nsum of dim=0")
# result = tensor.sum(dim=0)
# print(result)

# print("\nsum of dim=1")
# result = tensor.sum(dim=1)
# print(result)

tensor:
tensor([[ 20,  30,  50],
        [100,  10,  60]])

--------------------------------------------------
sum of entire tensor:
tensor(270)

--------------------------------------------------
sum of (dim=0):
tensor([120,  40, 110])

--------------------------------------------------
sum of (dim=1):
tensor([100, 170])


---

## mean, argmax, argmin

- `torch.mean()` or `tensor.mean()`

- `torch.argmax()` or `tensor.argmax()`

- `torch.argmin()` or `tensor.argmin()`


In [30]:
tensor = torch.tensor([[20, 30, 50], [100, 10, 60]], dtype=torch.float)
print(f"tensor:\n{tensor}")

print(f"\n{'-' * 50}")
print("mean of entire tensor:")
print(torch.mean(tensor))

print(f"\n{'-' * 50}")
print("mean of (dim=0):")
result = torch.mean(tensor, dim=0)
print(result)

print(f"\n{'-' * 50}")
print("mean of (dim=1):")
result = torch.mean(tensor, dim=1)
print(result)

# print(tensor.mean())

# print("\nmean of dim=0")
# result = tensor.mean(dim=0)
# print(result)

# print("\nmean of dim=1")
# result = tensor.mean(dim=1)
# print(result)

tensor:
tensor([[ 20.,  30.,  50.],
        [100.,  10.,  60.]])

--------------------------------------------------
mean of entire tensor:
tensor(45.)

--------------------------------------------------
mean of (dim=0):
tensor([60., 20., 55.])

--------------------------------------------------
mean of (dim=1):
tensor([33.3333, 56.6667])


In [31]:
tensor = torch.tensor([[20, 30, 50], [100, 10, 60]])
print(f"tensor:\n{tensor}")

print(f"\n{'-' * 50}")
print("argmax of entire tensor:")
print(torch.argmax(tensor))


print(f"\n{'-' * 50}")
print("argmax of (dim=0):")
result = torch.argmax(tensor, dim=0)
print(result)

print(f"\n{'-' * 50}")
print("argmax of (dim=1):")
result = torch.argmax(tensor, dim=1)
print(result)

# print(tensor.argmax())

# print("\nargmax of dim=0")
# result = tensor.argmax(dim=0)
# print(result)

# print("\nargmax of dim=1")
# result = tensor.argmax(dim=1)
# print(result)

tensor:
tensor([[ 20,  30,  50],
        [100,  10,  60]])

--------------------------------------------------
argmax of entire tensor:
tensor(3)

--------------------------------------------------
argmax of (dim=0):
tensor([1, 0, 1])

--------------------------------------------------
argmax of (dim=1):
tensor([2, 0])


In [32]:
tensor = torch.tensor([[20, 30, 50], [100, 10, 60]], dtype=torch.float)
print(f"tensor:\n{tensor}")

print(f"\n{'-' * 50}")
print("argmin of entire tensor:")
print(torch.argmin(tensor))

print(f"\n{'-' * 50}")
print("argmin of (dim=0):")
result = torch.argmin(tensor, dim=0)
print(result)

print(f"\n{'-' * 50}")
print("argmin of (dim=1):")
result = torch.argmin(tensor, dim=1)
print(result)

# print(tensor.argmin())

# print("\nargmin of dim=0")
# result = tensor.argmin(dim=0)
# print(result)

# print("\nargmin of dim=1")
# result = tensor.argmin(dim=1)
# print(result)

tensor:
tensor([[ 20.,  30.,  50.],
        [100.,  10.,  60.]])

--------------------------------------------------
argmin of entire tensor:
tensor(4)

--------------------------------------------------
argmin of (dim=0):
tensor([0, 1, 0])

--------------------------------------------------
argmin of (dim=1):
tensor([0, 1])


---

## stack, hstack, vstack

- `torch.stack()`

- `torch.hstack()`

- `torch.vstack()`


In [33]:
tensor1 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
tensor2 = torch.tensor([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print(f"tensor1:\n{tensor1}")
print(f"shape: {tensor1.shape}")

print(f"\ntensor2:\n{tensor2}")
print(f"shape: {tensor2.shape}")
print("-" * 50)

result = torch.stack((tensor1, tensor2)) # default: dim=0
print(f"\nstacked tensor (dim=0):\n{result}")
print(f"stacked dtype: {result.shape}")
print("-" * 50)

result = torch.stack((tensor1, tensor2), dim=1)
print(f"\nstacked tensor (dim=1):\n{result}")
print(f"stacked dtype: {result.shape}")
print("-" * 50)

result = torch.stack((tensor1, tensor2), dim=2)
print(f"\nstacked tensor (dim=2):\n{result}")
print(f"stacked dtype: {result.shape}")
print("-" * 50)


tensor1:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
shape: torch.Size([3, 4])

tensor2:
tensor([[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])
shape: torch.Size([3, 4])
--------------------------------------------------

stacked tensor (dim=0):
tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ 10,  20,  30,  40],
         [ 50,  60,  70,  80],
         [ 90, 100, 110, 120]]])
stacked dtype: torch.Size([2, 3, 4])
--------------------------------------------------

stacked tensor (dim=1):
tensor([[[  1,   2,   3,   4],
         [ 10,  20,  30,  40]],

        [[  5,   6,   7,   8],
         [ 50,  60,  70,  80]],

        [[  9,  10,  11,  12],
         [ 90, 100, 110, 120]]])
stacked dtype: torch.Size([3, 2, 4])
--------------------------------------------------

stacked tensor (dim=2):
tensor([[[  1,  10],
         [  2,  20],
         [  3,  30],
         [  

In [34]:
tensor1 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
tensor2 = torch.tensor([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print(f"tensor1:\n{tensor1}")
print(f"shape: {tensor1.shape}")

print(f"\ntensor2:\n{tensor2}")
print(f"shape: {tensor2.shape}")
print("-" * 50)

result = torch.hstack((tensor1, tensor2))
print(f"\nhorizontally stacked tensor:\n{result}")
print(f"stacked dtype: {result.shape}")
print("-" * 50)

result = torch.vstack((tensor1, tensor2))
print(f"\nvertically stacked tensor:\n{result}")
print(f"stacked dtype: {result.shape}")
print("-" * 50)


tensor1:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
shape: torch.Size([3, 4])

tensor2:
tensor([[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])
shape: torch.Size([3, 4])
--------------------------------------------------

horizontally stacked tensor:
tensor([[  1,   2,   3,   4,  10,  20,  30,  40],
        [  5,   6,   7,   8,  50,  60,  70,  80],
        [  9,  10,  11,  12,  90, 100, 110, 120]])
stacked dtype: torch.Size([3, 8])
--------------------------------------------------

vertically stacked tensor:
tensor([[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])
stacked dtype: torch.Size([6, 4])
--------------------------------------------------


---

## squeeze, unsqueeze, permute

- `torch.squeeze()` or `tensor.squeeze()`

- `torch.unsqueeze()` or `tensor.unsqueeze()`

- `torch.permute()` or `tensor.permute()`

In [35]:
tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"tensor:\n{tensor}")
print(f"shape: {tensor.shape}")
print("-" * 50)

result = torch.unsqueeze(tensor, dim=0)
print(f"\nunsqueeze (dim=0):\n{result}")
print(f"shape: {result.shape}")
print("-" * 50)

result = torch.unsqueeze(tensor, dim=1)
print(f"\nunsqueeze (dim=1):\n{result}")
print(f"shape: {result.shape}")
print("-" * 50)

result = torch.unsqueeze(tensor, dim=2)
print(f"\nunsqueeze (dim=2):\n{result}")
print(f"shape: {result.shape}")
print("-" * 50)

# result = tensor.unsqueeze(dim=0)
# print(f"\nunsqueeze (dim=0):\n{result}")
# print(f"shape: {result.shape}")
# print("-" * 50)

# result = tensor.unsqueeze(dim=1)
# print(f"\nunsqueeze (dim=1):\n{result}")
# print(f"shape: {result.shape}")
# print("-" * 50)

# result = tensor.unsqueeze(dim=2)
# print(f"\nunsqueeze (dim=2):\n{result}")
# print(f"shape: {result.shape}")
# print("-" * 50)

tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
shape: torch.Size([3, 4])
--------------------------------------------------

unsqueeze (dim=0):
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])
shape: torch.Size([1, 3, 4])
--------------------------------------------------

unsqueeze (dim=1):
tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]])
shape: torch.Size([3, 1, 4])
--------------------------------------------------

unsqueeze (dim=2):
tensor([[[ 1],
         [ 2],
         [ 3],
         [ 4]],

        [[ 5],
         [ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11],
         [12]]])
shape: torch.Size([3, 4, 1])
--------------------------------------------------


In [36]:
tensor = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])
print(f"tensor:\n{tensor}")
print(f"shape: {tensor.shape}")
print("-" * 50)

result = torch.squeeze(tensor)
print(f"\nsqueeze:\n{result}")
print(f"shape: {result.shape}")
print("-" * 50)

# result = tensor.squeeze()
# print(f"\nsqueeze:\n{result}")
# print(f"shape: {result.shape}")
# print("-" * 50)


tensor:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])
shape: torch.Size([1, 3, 4])
--------------------------------------------------

squeeze:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
shape: torch.Size([3, 4])
--------------------------------------------------


In [37]:
tensor = torch.tensor([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])
print(f"tensor:\n{tensor}")
print(f"shape: {tensor.shape}")
print("-" * 50)

result = torch.permute(tensor, dims=(2, 0, 1))
print(f"\npermute:\n{result}")
print(f"shape: {result.shape}")
print("-" * 50)

# result = tensor.permute(dims=(2, 0, 1))
# print(f"\nunsqueeze:\n{result}")
# print(f"shape: {result.shape}")
# print("-" * 50)


tensor:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])
shape: torch.Size([1, 3, 4])
--------------------------------------------------

permute:
tensor([[[ 1,  5,  9]],

        [[ 2,  6, 10]],

        [[ 3,  7, 11]],

        [[ 4,  8, 12]]])
shape: torch.Size([4, 1, 3])
--------------------------------------------------


## view, to, from_numpy, numpy

- `torch.view()` or `tensor.view()`

- `torch.to()` or `tensor.to()`

- `torch.from_numpy()`

- `tensor.numpy()`

In [38]:
tensor = torch.tensor([[20, 10], [30, 40]])
print(f"tensor:\n{tensor}")
print(f"shape: {tensor.shape}")
print("-" * 50)

result = tensor.view(size=(1, 4))
print(f"\nview: {result}")
print(f"shape: {result.shape}")
print("-" * 50)

result[0, 3] = 999

print(f"tensor:\n{tensor}")
print("-" * 50)

result = tensor.view(size=(1, 4))
print(f"\nview: {result}")
print("-" * 50)

tensor:
tensor([[20, 10],
        [30, 40]])
shape: torch.Size([2, 2])
--------------------------------------------------

view: tensor([[20, 10, 30, 40]])
shape: torch.Size([1, 4])
--------------------------------------------------
tensor:
tensor([[ 20,  10],
        [ 30, 999]])
--------------------------------------------------

view: tensor([[ 20,  10,  30, 999]])
--------------------------------------------------


In [39]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"devive: {device}")
cuda_count = torch.cuda.device_count()
print(f"cuda counts: {cuda_count}")
print("-" * 50)

tensor = torch.tensor([[20, 10], [30, 40]])
print(f"tensor:\n{tensor}")
print(f"device: {tensor.device}")
print("-" * 50)

result = tensor.to(device)
print(f"\nto device:\n{result}")
print(f"device: {result.device}")
print("-" * 50)


devive: cpu
cuda counts: 0
--------------------------------------------------
tensor:
tensor([[20, 10],
        [30, 40]])
device: cpu
--------------------------------------------------

to device:
tensor([[20, 10],
        [30, 40]])
device: cpu
--------------------------------------------------


In [40]:
import numpy as np

arr = np.arange(10, 20)
print(f"numpy array:\n{arr}")
print(f"dtype : {arr.dtype}")
print("-" * 50)

tensor = torch.from_numpy(arr)
print(f"tensor form numpy:\n{tensor}")
print(f"dtype : {tensor.dtype}")
print(f"device: {tensor.device}")
print("-" * 50)

numpy_from_tensor = tensor.numpy()
print(f"numpy from tensor:\n{numpy_from_tensor}")
print(f"dtype : {numpy_from_tensor.dtype}")
print("-" * 50)

numpy array:
[10 11 12 13 14 15 16 17 18 19]
dtype : int64
--------------------------------------------------
tensor form numpy:
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
dtype : torch.int64
device: cpu
--------------------------------------------------
numpy from tensor:
[10 11 12 13 14 15 16 17 18 19]
dtype : int64
--------------------------------------------------
